### ISSUE TITLE
Incompatible with bro 2.5-6

### ISSUE THREAD

**Issue by dopheide-esnet** [ncsa/bro-simple-scan#1]
Due to different arguments for the begin_suppression event in /frameworks/notice/main.bro

Works fine with bro 2.5-297.

**Comment by JustinAzoff** [comment]
Ah, yes.. It would be!  That was changed in

```
2.5-140 | 2017-05-12 15:31:32 -0400

  * Lessen cluster load due to notice suppression.
    (Johanna Amann, Justin Azoff)
```

I think I just need to set 2.5.1 as the minimum required version in the pkg metadata.

I could probably support both methods with the same script, but I'd rather encourage people to upgrade to 2.5.1 which has a ton of other fixes :)

**Comment by JustinAzoff** [comment]
Added dependency in commit 10e04bfd1c20324bcd2411f0ffee92db68e1816e
