### ISSUE TITLE
problem installing package using zkg package manager

### ISSUE THREAD

**Issue by dataolle** [ncsa/bro-simple-scan#5]
I get this error when trying to install:
$ zkg install ncsa/bro-simple-scan
error: failed to resolve dependencies: package "zeek/ncsa/bro-simple-scan" has invalid dependency "bro/ncsa/bro-is-darknet": package name not found in sources and also not a usable git URL (invalid or inaccessible, use -vvv for details)

**Comment by JustinAzoff** [comment]
Hi,  I just had to remove the bro/ prefix, now it should install on 2.6.x and on 3.x

**Comment by dataolle** [comment]
Thanks!
