### ISSUE TITLE
Tests breaks on newer versions of zeek - calls bro and bro-cut binarys instead of zeek

### ISSUE THREAD

**Issue by dataolle** [ncsa/bro-simple-scan#8]
Installation failes when running unit tests using zkg.
Looks like the unit tests are using old binarys "bro" and "bro-cut".
This is causeing installation to fail using zkg since these binarys are symlinks to zeek-wrapper now.
Easy to fix is to remove the symlink to the actual binarys instead but this should really be fixed in the package.

Running zeek version 3.1.5

**Comment by JustinAzoff** [comment]
Fixed in c04a1e7a850d3cae486e6610c899bd59d59a89f2 and tagged as 2.0
